frr version 10.4.1_git
frr defaults traditional
hostname as6_r0
!
ip prefix-list AS6_networks description My AS6 Networks
ip prefix-list AS6_networks seq 5 permit 106.0.0.0/24
ip prefix-list AS6_networks seq 10 permit 106.1.0.0/16 le 24
ip prefix-list AS6_networks seq 15 permit 206.0.0.0/15 le 24
!
ipv6 prefix-list AS6_networks_v6 description My AS6 IPv6 Networks
ipv6 prefix-list AS6_networks_v6 seq 5 permit 2000:6666::/32
!
route-map peers_out permit 10
 match ip address prefix-list AS6_networks
 set community 6:100 additive
 set metric 10
exit
!
route-map peers_out permit 15
 match ipv6 address prefix-list AS6_networks_v6
 set community 6:100 additive
 set metric 10
exit
!
route-map peers_out deny 999
exit
!
route-map peers_in permit 10
exit
!
ip route 106.1.0.0/16 blackhole 254
ip route 206.0.0.0/15 blackhole 254
ip route 106.0.0.0/24 blackhole 254
ipv6 route 2000:6666::/32 blackhole 254
!
interface eth1
 description to AS6_H1
 ip address 206.0.0.1/30
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:6666:6:ffff::1/64
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
interface eth2
 description connection to AS5
 ip address 105.1.0.2/30
exit
!
interface lo
 description AS6 R0 Loopback
 ip address 106.0.0.0/32
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:6666:6::/128
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
router bgp 6
 bgp router-id 106.0.0.0
 bgp log-neighbor-changes
 neighbor 105.1.0.1 remote-as 5
 neighbor 105.1.0.1 description AS5
 !
 address-family ipv4 unicast
  network 106.0.0.0/24
  network 106.1.0.0/16
  network 206.0.0.0/15
  neighbor 105.1.0.1 next-hop-self
  neighbor 105.1.0.1 route-map peers_in in
  neighbor 105.1.0.1 route-map peers_out out
 exit-address-family
 !
 address-family ipv6 unicast
  network 2000:6666::/32
  neighbor 105.1.0.1 activate
  neighbor 105.1.0.1 next-hop-self
  neighbor 105.1.0.1 route-map peers_in in
  neighbor 105.1.0.1 route-map peers_out out
 exit-address-family
exit
!
router ospf
 ospf router-id 106.0.0.0
 redistribute connected metric-type 1
exit
!
router ospf6
 ospf6 router-id 106.0.0.0
 redistribute connected metric-type 1
exit
!
