frr version 10.4.1_git
frr defaults traditional
hostname as1-r0
!
ip prefix-list AS1_networks description My AS1 Networks
ip prefix-list AS1_networks seq 5 permit 101.0.0.0/8 le 24
ip prefix-list AS1_networks seq 10 permit 201.0.0.0/8 le 24
ip prefix-list AS1_transit_networks description Networks for Transit
!
route-map peers_out permit 10
 match ip address prefix-list AS1_networks
 set community 1:100 additive
 set metric 10
exit
!
route-map peers_out permit 20
 match ip address prefix-list AS1_transit_networks
exit
!
route-map peers_out deny 999
exit
!
route-map peers_in permit 10
exit
!
ip route 101.1.0.0/16 blackhole 254
ip route 201.0.0.0/16 blackhole 254
ip route 101.0.0.0/24 blackhole 254
!
interface eth1
 description connection to AS1-H1
 ip address 201.0.0.1/30
 ip ospf area 0
 ip ospf passive
exit
!
interface eth2
 description connection to AS2
 ip address 101.1.0.1/30
exit
!
interface eth3
 description connection to AS3
 ip address 101.1.0.5/30
exit
!
interface lo
 description AS1 R0 Loopback
 ip address 101.0.0.0/32
 ip ospf area 0
 ip ospf passive
exit
!
router bgp 1
 bgp router-id 101.0.0.0
 bgp log-neighbor-changes
 neighbor 101.1.0.2 remote-as 2
 neighbor 101.1.0.2 description AS2
 neighbor 101.1.0.6 remote-as 3
 neighbor 101.1.0.6 description AS3
 !
 address-family ipv4 unicast
  network 101.0.0.0/24
  network 101.1.0.0/16
  network 201.0.0.0/16
  neighbor 101.1.0.2 next-hop-self
  neighbor 101.1.0.2 route-map peers_in in
  neighbor 101.1.0.2 route-map peers_out out
  neighbor 101.1.0.6 next-hop-self
  neighbor 101.1.0.6 route-map peers_in in
  neighbor 101.1.0.6 route-map peers_out out
 exit-address-family
exit
!
router ospf
 ospf router-id 101.0.0.0
 redistribute connected metric-type 1
exit
!
