frr version 10.4.1_git
frr defaults traditional
hostname as8_r0
!
ip prefix-list AS8_networks description My AS8 Networks
ip prefix-list AS8_networks seq 5 permit 108.0.0.0/24
ip prefix-list AS8_networks seq 10 permit 108.1.0.0/16 le 24
ip prefix-list AS8_networks seq 15 permit 208.0.0.0/15 le 24
!
ipv6 prefix-list AS8_networks_v6 description My AS8 IPv6 Networks
ipv6 prefix-list AS8_networks_v6 seq 5 permit 2000:8888::/32
!
route-map peers_out permit 10
 match ip address prefix-list AS8_networks
 set community 8:100 additive
 set metric 10
exit
!
route-map peers_out permit 15
 match ipv6 address prefix-list AS8_networks_v6
 set community 8:100 additive
 set metric 10
exit
!
route-map peers_out permit 20
 match as-path transit_as
exit
!
route-map peers_out deny 999
exit
!
route-map peers_in permit 10
exit
!
ip route 108.1.0.0/16 blackhole 254
ip route 208.0.0.0/15 blackhole 254
ip route 108.0.0.0/24 blackhole 254
ipv6 route 2000:8888::/32 blackhole 254
!
interface eth1
 description to AS8_H1
 ip address 208.0.0.1/30
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:8888:8:ffff::1/64
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
interface eth2
 description connection to AS4
 ip address 104.1.0.2/30
exit
!
interface eth3
 description connection to AS9
 ip address 108.1.0.1/30
exit
!
interface lo
 description AS8 R0 Loopback
 ip address 108.0.0.0/32
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:8888:8::/128
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
router bgp 8
 bgp router-id 108.0.0.0
 bgp log-neighbor-changes
 neighbor 104.1.0.1 remote-as 4
 neighbor 104.1.0.1 description AS4
 neighbor 108.1.0.2 remote-as 9
 neighbor 108.1.0.2 description AS9
 !
 address-family ipv4 unicast
  network 108.0.0.0/24
  network 108.1.0.0/16
  network 208.0.0.0/15
  neighbor 104.1.0.1 next-hop-self
  neighbor 104.1.0.1 route-map peers_in in
  neighbor 104.1.0.1 route-map peers_out out
  neighbor 108.1.0.2 next-hop-self
  neighbor 108.1.0.2 route-map peers_in in
  neighbor 108.1.0.2 route-map peers_out out
 exit-address-family
 !
 address-family ipv6 unicast
  network 2000:8888::/32
  neighbor 104.1.0.1 activate
  neighbor 104.1.0.1 next-hop-self
  neighbor 104.1.0.1 route-map peers_in in
  neighbor 104.1.0.1 route-map peers_out out
  neighbor 108.1.0.2 activate
  neighbor 108.1.0.2 next-hop-self
  neighbor 108.1.0.2 route-map peers_in in
  neighbor 108.1.0.2 route-map peers_out out
 exit-address-family
exit
!
router ospf
 ospf router-id 108.0.0.0
 redistribute connected metric-type 1
exit
!
router ospf6
 ospf6 router-id 108.0.0.0
 redistribute connected metric-type 1
exit
!
bgp as-path access-list transit_as seq 5 permit ^4_
bgp as-path access-list transit_as seq 10 permit ^9_
!
