frr version 10.4.1_git
frr defaults traditional
hostname as5_r0
!
ip prefix-list AS5_transit_networks description Networks for Transit
ip prefix-list AS5_networks description My AS5 Networks
ip prefix-list AS5_networks seq 5 permit 105.0.0.0/24
ip prefix-list AS5_networks seq 10 permit 105.1.0.0/16 le 24
ip prefix-list AS5_networks seq 15 permit 205.0.0.0/15 le 24
!
ipv6 prefix-list AS5_networks_v6 description My AS5 IPv6 Networks
ipv6 prefix-list AS5_networks_v6 seq 5 permit 2000:5555::/32
!
route-map peers_out permit 10
 match ip address prefix-list AS5_networks
 set community 5:100 additive
 set metric 10
exit
!
route-map peers_out permit 15
 match ipv6 address prefix-list AS5_networks_v6
 set community 5:100 additive
 set metric 10
exit
!
route-map peers_out permit 20
 match as-path transit_as
exit
!
route-map peers_out deny 999
exit
!
route-map peers_in permit 10
exit
!
ip route 105.1.0.0/16 blackhole 254
ip route 205.0.0.0/15 blackhole 254
ip route 105.0.0.0/24 blackhole 254
ipv6 route 2000:5555::/32 blackhole 254
!
interface eth1
 description to AS5_H1
 ip address 205.0.0.1/30
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:5555:5:ffff::1/64
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
interface eth2
 description connection to AS1
 ip address 101.1.1.26/30
exit
!
interface eth3
 description connection to AS2
 ip address 102.1.0.18/30
exit
!
interface eth4
 description connection to AS6
 ip address 105.1.0.1/30
exit
!
interface lo
 description AS5 R0 Loopback
 ip address 105.0.0.0/32
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:5555:5::/128
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
router bgp 5
 bgp router-id 105.0.0.0
 bgp log-neighbor-changes
 neighbor 101.1.1.25 remote-as 1
 neighbor 101.1.1.25 description AS1
 neighbor 102.1.0.17 remote-as 2
 neighbor 102.1.0.17 description AS2
 neighbor 105.1.0.2 remote-as 6
 neighbor 105.1.0.2 description AS6
 !
 address-family ipv4 unicast
  network 105.0.0.0/24
  network 105.1.0.0/16
  network 205.0.0.0/15
  neighbor 101.1.1.25 next-hop-self
  neighbor 101.1.1.25 route-map peers_in in
  neighbor 101.1.1.25 route-map peers_out out
  neighbor 102.1.0.17 next-hop-self
  neighbor 102.1.0.17 route-map peers_in in
  neighbor 102.1.0.17 route-map peers_out out
  neighbor 105.1.0.2 next-hop-self
  neighbor 105.1.0.2 route-map peers_in in
  neighbor 105.1.0.2 route-map peers_out out
 exit-address-family
 !
 address-family ipv6 unicast
  network 2000:5555::/32
  neighbor 101.1.1.25 activate
  neighbor 101.1.1.25 next-hop-self
  neighbor 101.1.1.25 route-map peers_in in
  neighbor 101.1.1.25 route-map peers_out out
  neighbor 102.1.0.17 activate
  neighbor 102.1.0.17 next-hop-self
  neighbor 102.1.0.17 route-map peers_in in
  neighbor 102.1.0.17 route-map peers_out out
  neighbor 105.1.0.2 activate
  neighbor 105.1.0.2 next-hop-self
  neighbor 105.1.0.2 route-map peers_in in
  neighbor 105.1.0.2 route-map peers_out out
 exit-address-family
exit
!
router ospf
 ospf router-id 105.0.0.0
 redistribute connected metric-type 1
exit
!
router ospf6
 ospf6 router-id 105.0.0.0
 redistribute connected metric-type 1
exit
!
bgp as-path access-list transit_as seq 5 permit ^6_
bgp as-path access-list transit_as seq 10 permit ^2_
bgp as-path access-list transit_as seq 15 permit ^1_
!
