frr version 10.4.1_git
frr defaults traditional
hostname as7_r0
!
ip prefix-list AS7_networks description My AS7 Networks
ip prefix-list AS7_networks seq 5 permit 107.0.0.0/24
ip prefix-list AS7_networks seq 10 permit 107.1.0.0/16 le 24
ip prefix-list AS7_networks seq 15 permit 207.0.0.0/15 le 24
ip prefix-list AS7_transit_networks description Networks for Transit
!
ipv6 prefix-list AS7_networks_v6 description My AS7 IPv6 Networks
ipv6 prefix-list AS7_networks_v6 seq 5 permit 2000:7777::/32
!
route-map peers_out permit 10
 match ip address prefix-list AS7_networks
 set community 7:100 additive
 set metric 10
exit
!
route-map peers_out permit 15
 match ipv6 address prefix-list AS7_networks_v6
 set community 7:100 additive
 set metric 10
exit
!
route-map peers_out permit 20
 match as-path transit_as
exit
!
route-map peers_out deny 999
exit
!
route-map peers_in permit 10
exit
!
ip route 107.1.0.0/16 blackhole 254
ip route 207.0.0.0/15 blackhole 254
ip route 107.0.0.0/24 blackhole 254
ipv6 route 2000:7777::/32 blackhole 254
!
interface eth1
 description to AS7_H1
 ip address 207.0.0.1/30
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:7777:7:ffff::1/64
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
interface eth2
 description connection to AS1
 ip address 101.1.1.30/30
exit
!
interface eth3
 description connection to AS3
 ip address 103.1.0.6/30
exit
!
interface eth4
 description connection to AS9
 ip address 107.1.0.1/30
exit
!
interface lo
 description AS7 R0 Loopback
 ip address 107.0.0.0/32
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:7777:7::/128
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
router bgp 7
 bgp router-id 107.0.0.0
 bgp log-neighbor-changes
 neighbor 101.1.1.29 remote-as 1
 neighbor 101.1.1.29 description AS1
 neighbor 103.1.0.5 remote-as 3
 neighbor 103.1.0.5 description AS3
 neighbor 107.1.0.2 remote-as 9
 neighbor 107.1.0.2 description AS9
 !
 address-family ipv4 unicast
  network 107.0.0.0/24
  network 107.1.0.0/16
  network 207.0.0.0/15
  neighbor 101.1.1.29 next-hop-self
  neighbor 101.1.1.29 route-map peers_in in
  neighbor 101.1.1.29 route-map peers_out out
  neighbor 103.1.0.5 next-hop-self
  neighbor 103.1.0.5 route-map peers_in in
  neighbor 103.1.0.5 route-map peers_out out
  neighbor 107.1.0.2 next-hop-self
  neighbor 107.1.0.2 route-map peers_in in
  neighbor 107.1.0.2 route-map peers_out out
 exit-address-family
 !
 address-family ipv6 unicast
  network 2000:7777::/32
  neighbor 101.1.1.29 activate
  neighbor 101.1.1.29 next-hop-self
  neighbor 101.1.1.29 route-map peers_in in
  neighbor 101.1.1.29 route-map peers_out out
  neighbor 103.1.0.5 activate
  neighbor 103.1.0.5 next-hop-self
  neighbor 103.1.0.5 route-map peers_in in
  neighbor 103.1.0.5 route-map peers_out out
  neighbor 107.1.0.2 activate
  neighbor 107.1.0.2 next-hop-self
  neighbor 107.1.0.2 route-map peers_in in
  neighbor 107.1.0.2 route-map peers_out out
 exit-address-family
exit
!
router ospf
 ospf router-id 107.0.0.0
 redistribute connected metric-type 1
exit
!
router ospf6
 ospf6 router-id 107.0.0.0
 redistribute connected metric-type 1
exit
!
bgp as-path access-list transit_as seq 5 permit ^3_
bgp as-path access-list transit_as seq 10 permit ^1_
bgp as-path access-list transit_as seq 15 permit ^9_
!
