frr version 10.4.1_git
frr defaults traditional
hostname as4_r0
!
ip prefix-list AS4_networks description My AS4 Networks
ip prefix-list AS4_networks seq 5 permit 104.0.0.0/24
ip prefix-list AS4_networks seq 10 permit 104.1.0.0/16 le 24
ip prefix-list AS4_networks seq 15 permit 204.0.0.0/15 le 24
ip prefix-list AS4_transit_networks description Networks for Transit
!
ipv6 prefix-list AS4_networks_v6 description My AS4 IPv6 Networks
ipv6 prefix-list AS4_networks_v6 seq 5 permit 2000:4444::/32
!
route-map peers_out permit 10
 match ip address prefix-list AS4_networks
 set community 1:100 additive
 set metric 10
exit
!
route-map peers_out permit 15
 match ipv6 address prefix-list AS4_networks_v6
 set community 2:100 additive
 set metric 10
exit
!
route-map peers_out permit 20
 match as-path transit_as
exit
!
route-map peers_out deny 999
exit
!
route-map peers_in permit 10
exit
!
ip route 104.1.0.0/16 blackhole 254
ip route 204.0.0.0/15 blackhole 254
ip route 104.0.0.0/24 blackhole 254
ipv6 route 2000:4444::/32 blackhole 254
!
interface eth1
 description connection to AS4-H1
 ip address 204.0.0.1/30
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:4444:4:ffff::1/64
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
interface eth2
 description connection to AS2
 ip address 102.1.0.10/30
exit
!
interface eth3
 description connection to AS2
 ip address 102.1.0.14/30
exit
!
interface eth4
 description connection to AS2
 ip address 103.1.0.2/30
exit
!
interface eth5
 description connection to AS8
 ip address 104.1.0.1/30
exit
!
interface lo
 description AS4 R0 Loopback
 ip address 104.0.0.0/32
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:4444:4::/128
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
router bgp 4
 bgp router-id 104.0.0.0
 bgp log-neighbor-changes
 neighbor 102.1.0.9 remote-as 2
 neighbor 102.1.0.9 description AS2
 neighbor 102.1.0.13 remote-as 2
 neighbor 102.1.0.13 description AS2
 neighbor 103.1.0.1 remote-as 3
 neighbor 103.1.0.1 description AS3
 neighbor 104.1.0.2 remote-as 8
 neighbor 104.1.0.2 description AS8
 !
 address-family ipv4 unicast
  network 104.0.0.0/24
  network 104.1.0.0/16
  network 204.0.0.0/15
  neighbor 102.1.0.9 next-hop-self
  neighbor 102.1.0.9 route-map peers_in in
  neighbor 102.1.0.9 route-map peers_out out
  neighbor 102.1.0.13 next-hop-self
  neighbor 102.1.0.13 route-map peers_in in
  neighbor 102.1.0.13 route-map peers_out out
  neighbor 103.1.0.1 next-hop-self
  neighbor 103.1.0.1 route-map peers_in in
  neighbor 103.1.0.1 route-map peers_out out
  neighbor 104.1.0.2 next-hop-self
  neighbor 104.1.0.2 route-map peers_in in
  neighbor 104.1.0.2 route-map peers_out out
 exit-address-family
 !
 address-family ipv6 unicast
  network 2000:4444::/32
  neighbor 102.1.0.9 activate
  neighbor 102.1.0.9 next-hop-self
  neighbor 102.1.0.9 route-map peers_in in
  neighbor 102.1.0.9 route-map peers_out out
  neighbor 102.1.0.13 activate
  neighbor 102.1.0.13 next-hop-self
  neighbor 102.1.0.13 route-map peers_in in
  neighbor 102.1.0.13 route-map peers_out out
  neighbor 103.1.0.1 activate
  neighbor 103.1.0.1 next-hop-self
  neighbor 103.1.0.1 route-map peers_in in
  neighbor 103.1.0.1 route-map peers_out out
  neighbor 104.1.0.2 activate
  neighbor 104.1.0.2 next-hop-self
  neighbor 104.1.0.2 route-map peers_in in
  neighbor 104.1.0.2 route-map peers_out out
 exit-address-family
exit
!
router ospf
 ospf router-id 104.0.0.0
 redistribute connected metric-type 1
exit
!
router ospf6
 ospf6 router-id 104.0.0.0
 redistribute connected metric-type 1
exit
!
bgp as-path access-list transit_as seq 5 permit ^2_
bgp as-path access-list transit_as seq 10 permit ^3_
bgp as-path access-list transit_as seq 15 permit ^8_
!
