frr version 10.4.1_git
frr defaults traditional
hostname as1_r5
!
interface eth1
 description connection to AS1-H2
 ip address 201.0.1.1/24
 ip ospf area 0
 ip ospf passive
 ipv6 address 2000:1111:1:ffff::1/64
 ipv6 ospf6 area 0
 ipv6 ospf6 passive
exit
!
interface eth2
 description connection to AS1-R3
 ip address 101.1.1.18/30
 ip ospf area 0
 ipv6 address 2000:1111:1:305::2/64
 ipv6 ospf6 area 0
exit
!
interface eth3
 description connection to AS1-R4
 ip address 101.1.1.22/30
 ip ospf area 0
 ipv6 address 2000:1111:1:405::2/64
 ipv6 ospf6 area 0
exit
!
interface lo
 description AS1 R5 Loopback
 ip address 101.0.0.5/32
 ip ospf area 0
 ipv6 address 2000:1111:1::5/128
 ipv6 ospf6 area 0
exit
!
router ospf
 ospf router-id 101.0.0.5
 redistribute connected metric-type 1
exit
!
router ospf6
 ospf6 router-id 101.0.0.5
 redistribute connected metric-type 1
exit
!
